services:
  - type: web
    name: nocodb
    env: docker
    repo: https://github.com/nocodb/nocodb
    branch: main
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: NC_DB
        fromDatabase:
          name: nocodb-db
          property: connectionString
      - key: NC_PUBLIC_URL
        value: https://nocodb.onrender.com # Replace with actual Render URL after deploy

databases:
  - name: nocodb-db
    databaseName: nocodb
    user: nocodbuser
    plan: free
